samples: "samples.tsv"
units: "units.tsv"

reference:
  adapter:
    fwd: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA"
    rev: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG"
  fasta: ""

tools:
  fastp: "docker://marrip/fastp:0.21.0"
  ubuntu: "docker://ubuntu:18.04"
