samples: "samples.tsv"
units: "units.tsv"
pedigree: "pedigree.tsv"
filter: ""

reference:
  adapter:
    fwd: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA"
    rev: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG"
  fasta: ""
  dict: ""
  sites: ""
  dbsnp: ""

haplotypecaller:
  pon: ""

manta:
  pon: ""

snpeff:
  cfile: ""
  db: ""

tiddit:
  pon: ""

tools:
  common: "docker://marrip/common:1.0.0"
  fastp: "docker://marrip/fastp:0.21.0"
  fastqc: "docker://marrip/fastqc:0.11.9"
  gatk: "docker://broadinstitute/gatk:4.1.9.0"
  manta: "docker://marrip/manta:v1.6.0"
  mosdepth: "docker://marrip/mosdepth:v0.3.1"
  snpeff: "docker://marrip/snpeff:5.0c"
  tiddit: "docker://marrip/tiddit:2.12.1"
  ubuntu: "docker://ubuntu:18.04"
