$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  pedigree:
    type: string
  filter:
    type: string
  reference:
    type: object
    properties:
      adapter:
        type: object
        properties:
          fwd:
            type: string
          rev:
            type: string
        required:
          - fwd
          - rev
      fasta:
        type: string
      dict:
        type: string
      sites:
        type: string
      dbsnp:
        type: string
    required:
      - adapter
      - fasta
      - dict
      - sites
      - dbsnp
  haplotypecaller:
    type: object
    properties:
      pon:
        type: string
    required:
      - pon
  manta:
    type: object
    properties:
      pon:
        type: string
    required:
      - pon
  snpeff:
    type: object
    properties:
      cfile:
        type: string
      db:
        type: string
    required:
      - cfile
      - db
  tiddit:
    type: object
    properties:
      pon:
        type: string
    required:
      - pon
  tools:
    type: object
    properties:
      common:
        type: string
      fastp:
        type: string
      fastqc:
        type: string
      gatk:
        type: string
      manta:
        type: string
      mosdepth:
        type: string
      snpeff:
        type: string
      tiddit:
        type: string
      ubuntu:
        type: string
  required:
    - samples
    - units
    - pedigree
    - filter
    - reference
    - tools
