$schema: "http://json-schema.org/draft-04/schema#"
description: snakemake configuration file
type: object
properties:
  samples:
    type: string
  units:
    type: string
  pedigree:
    type: string
  filter:
    type: string
  reference:
    type: object
    properties:
      adapter:
        type: object
        properties:
          fwd:
            type: string
          rev:
            type: string
        required:
          - fwd
          - rev
      fasta:
        type: string
      dict:
        type: string
      sites:
        type: string
      dbsnp:
        type: string
      loci:
        type: array
    required:
      - adapter
      - fasta
      - dict
      - sites
      - dbsnp
      - loci
  tools:
    type: object
    properties:
      common:
        type: string
      fastp:
        type: string
      fastqc:
        type: string
      gatk:
        type: string
      ubuntu:
        type: string
  required:
    - samples
    - units
    - pedigree
    - filter
    - reference
    - tools
