samples: "samples.tsv"
units: "units.tsv"

reference:
  adapter:
    fwd: "AAGTCGGAGGCCAAGCGGTCTTAGGAAGACAA"
    rev: "AAGTCGGATCGTAGCCATGTCGTTCTGTGAGCCAAGGAGTTG"
  fasta: "reference/Homo_sapiens_AADACL3_sequence.fa"
  sites: "reference/known_indels.vcf"

tools:
  fastp: "docker://marrip/fastp:0.21.0"
  ubuntu: "docker://ubuntu:18.04"
