name: Lint Snakemake workflow

on:
  push:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Lint workflow
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v1
      - name: Linting
        uses: snakemake/snakemake-github-action@v1.15.0
        with:
          directory: ".tests/integration"
          snakefile: "Snakefile"
          args: "--lint"
